// <auto-generated />
using API2.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20260831095350_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Model.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InternalNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Robert C. Martin",
                            InternalNotes = "Bestseller, restock monthly",
                            Price = 35.99m,
                            Title = "Clean Code"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Andrew Hunt",
                            InternalNotes = "Popular with senior devs",
                            Price = 42.50m,
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Erich Gamma",
                            InternalNotes = "Slow mover, consider discount",
                            Price = 55.00m,
                            Title = "Design Patterns"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Martin Fowler",
                            InternalNotes = "New edition available",
                            Price = 39.99m,
                            Title = "Refactoring"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Kyle Simpson",
                            InternalNotes = "Free PDF also circulates online",
                            Price = 24.99m,
                            Title = "You Don't Know JS"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
