// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.EF;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(CMSDbContext))]
    partial class CMSDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.EF.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Physics"
                        });
                });

            modelBuilder.Entity("WebApplication1.EF.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("WebApplication1.EF.Admin", b =>
                {
                    b.HasBaseType("WebApplication1.EF.User");

                    b.Property<int>("AdminLevel")
                        .HasColumnType("int");

                    b.ToTable("Admins", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Age = 30,
                            BloodGroup = "B-",
                            Name = "David",
                            Password = "adminpassword1",
                            Role = "Admin",
                            AdminLevel = 1
                        },
                        new
                        {
                            Id = 5,
                            Age = 35,
                            BloodGroup = "AB+",
                            Name = "Eve",
                            Password = "adminpassword2",
                            Role = "Admin",
                            AdminLevel = 2
                        });
                });

            modelBuilder.Entity("WebApplication1.EF.Student", b =>
                {
                    b.HasBaseType("WebApplication1.EF.User");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterNumber")
                        .HasColumnType("int");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            BloodGroup = "O-",
                            Name = "Alice",
                            Password = "password1",
                            Role = "Student",
                            DepartmentId = 1,
                            SemesterNumber = 3
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            BloodGroup = "A+",
                            Name = "Bob",
                            Password = "password2",
                            Role = "Student",
                            DepartmentId = 2,
                            SemesterNumber = 5
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            BloodGroup = "O+",
                            Name = "Charlie",
                            Password = "password3",
                            Role = "Student",
                            DepartmentId = 3,
                            SemesterNumber = 1
                        });
                });

            modelBuilder.Entity("WebApplication1.EF.Admin", b =>
                {
                    b.HasOne("WebApplication1.EF.User", null)
                        .WithOne()
                        .HasForeignKey("WebApplication1.EF.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.EF.Student", b =>
                {
                    b.HasOne("WebApplication1.EF.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.EF.User", null)
                        .WithOne()
                        .HasForeignKey("WebApplication1.EF.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("WebApplication1.EF.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
